### ISSUE TITLE
I2C - Remote I/O error

### ISSUE THREAD

**Issue by dbmaxpayne** [blus-audio/sigmadsp#80] opened 2023-10-12 10:00 UTC
Hey,

Thanks for programming this first!
After using a USBi for a while, I was tired of it and found your project in hope to make things simpler, but I seem to be stuck getting things working.

I connect SDA, SCL, GND, 5V, RESET from a Raspberry Pi 3B to Wondom DSP (ADAU1701).
Atfer that I use `i2cdetect -y 1` to check if the device is available - it is on address 0x50 and 0x58.
Then I try to read some random registers with pigpio / pigs which seems to work.
Another I2C device is working perfectly, too.
That device is not active, though and also disconnected during my tests with sigmadsp.
After I create a project in SigmaStudio, I select TCPIP1701 and ADAU1701, connect them and set the IP address.
I then try do read the registers from within SigmaStudio, see the transmit LED on the Wondom DSP flickering for a split second and also see a short data burst in piscope on SCL/SDA.
However, I immediately get the following error:

INFO:sigmadsp.backend:Starting the sigmadsp backend, version 3.0.4.
INFO:sigmadsp.helper.settings:Settings file /var/lib/sigmadsp/config.yaml was loaded.
INFO:sigmadsp.helper.parser:Parameter file /var/lib/sigmadsp/current.params not found.
INFO:sigmadsp.protocols.common:Starting I2cProtocol handling thread.
  warnings.warn(
INFO:sigmadsp.dsp.common:Found DSP pin definition 'reset' (27)
INFO:sigmadsp.backend:Specified DSP type is 'Adau1x0x', using the 'I2cProtocol' protocol.
INFO:sigmadsp.dsp.common:Hard-resetting the DSP.
INFO:sigmadsp.dsp.adau1x01:Soft-reset is not available on ADAU1x01
INFO:sigmadsp.backend:Run startup safety check.
WARNING:sigmadsp.backend:No safety hash cell exists in the DSP configuration! Configuration remains locked.
INFO:sigmadsp.backend:Startup finished.
INFO:sigmadsp.backend:Backend service started on [::]:50051
INFO:sigmadsp.backend:Sigma TCP server started on [0.0.0.0]:8087.
Exception in thread I2cProtocol handler thread:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/.local/pipx/venvs/sigmadsp/lib/python3.9/site-packages/sigmadsp/protocols/common.py", line 68, in serve_forever
    data = self._read(request.address, request.length)
  File "/home/pi/.local/pipx/venvs/sigmadsp/lib/python3.9/site-packages/sigmadsp/protocols/i2c.py", line 49, in _read
    self._bus.i2c_rdwr(msg_wr, msg_rd)
  File "/home/pi/.local/pipx/venvs/sigmadsp/lib/python3.9/site-packages/smbus2/smbus2.py", line 658, in i2c_rdwr
    ioctl(self.fd, I2C_RDWR, ioctl_data)
OSError: [Errno 121] Remote I/O error

**Comment by elagil** [comment] 2023-10-12 14:54
@dbmaxpayne  Could you show your config.yaml?
Also, why does the DSP have two I2C addresses?

**Comment by dbmaxpayne** [comment] 2023-10-12 17:29
@elagil 

I guess because it has an EEPROM attached. I'm not entierely sure, though.
As there are no other devices connected to the I2C bus, I figured it must be the ADAU1701 and its ROM.

The config.yaml looks as follows:
-----------------------------------

# This  file contains all settings that can be changed on the sigmadsp-backend.

# The IP address and port, on which the sigmadsp-backend listens for requests from SigmaStudio.
host:
  # The default value "0.0.0.0" allows listening on any address.
  ip: "0.0.0.0"
  port: 8087

# Settings for the sigmadsp-backend.
backend:
  # The port, on which the sigmadsp-backend is reachable.
  port: 50051

parameters:
  # The parameter file path, which contains DSP application parameters,
  # such as cell names, addresses and other information. This parameter file is required
  # for the backend, in order to be able to control DSP functionality at runtime, e.g. volume.
  path: "/var/lib/sigmadsp/current.params"

dsp:
  # The type of the DSP to control with the sigmadsp-backend service.
  # Can be "adau14xx" or "adau1x0x".
  type: "adau1x0x"
  # The protocol used to communicate.
  # Can be "spi" or "i2c"
  protocol: "i2c"
  bus_number: "1"
  device_address: "0"

  pins:
    # The DSP's hardware reset pin.
    reset:
      number: 27
      active_high: false
      initial_state: true
      mode: "output"

    # Disabled as this is hardwired to self boot on the board
    # The self-boot pin, enabling the DSP to load its application from external flash when set.
    #self_boot:
    #  number: 22
    #  active_high: true
    #  initial_state: true
    #  mode: "output"

**Comment by elagil** [comment] 2023-10-12 17:44
As I suspected, you did not specify the device address. `sigmadsp` is not yet smart enough to automatically discover devices on the I2C bus, so you have to set the `device_address` to the correct value.

I think you have to specify it in base 10, so for example 80 for 0x50 or 88 for 0x58.

**Comment by elagil** [comment] 2023-10-13 14:43
Interesting, this might be an actual bug that I have not seen before.

I will check the packet definitions for your chip again, but I have no hardware to test it. You might have to pull a development version for verification.

**Comment by dbmaxpayne** [comment] 2023-10-13 14:46
No worries, happy to help and solve my problem at the same time :)

I have tried with SigmaStudio 3.15 and 4.7. The issue is the same.

**Comment by elagil** [comment] 2023-10-13 14:56
Yes, the issue is likely in https://github.com/blus-audio/sigmadsp/blob/main/sigmadsp/sigmastudio/adau1x01.py, as AnalogDevices has not published (to my knowledge) the TCP/IP packet structure for the 1401/1701 chipsets. I will add debug statements so that we can reverse engineer it.

Furthermore, I guess that you can specify the IC2 address in SigmaStudio. Is that correct? I might add functionality for using that address in order to access the target DSP.

**Comment by elagil** [comment] 2023-10-13 15:49
Yes, please `pipx upgrade sigmadsp`.

It will upgrade to v3.0.5. I added more useful assertion messages. Hopefully, this gives us a clue.

**Comment by dbmaxpayne** [comment] 2023-10-13 16:14
Thanks.
I now get the error below.
According to the [datasheet](https://www.analog.com/media/en/technical-documentation/data-sheets/ADAU1701.pdf) this is the first register being read.
Which is what I'm trying to do for a simple test in SigmaStudio (Hardware Configuration / IC1 Register Control / Read All).

```
Exception occurred during processing of request from ('192.168.178.24', 59453)
Traceback (most recent call last):
  File "/usr/lib/python3.9/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.9/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.9/socketserver.py", line 720, in __init__
    self.handle()
  File "/home/pi/.local/pipx/venvs/sigmadsp/lib/python3.9/site-packages/sigmadsp/sigmastudio/server.py", line 234, in handle
    self.handle_read_request(packet)
  File "/home/pi/.local/pipx/venvs/sigmadsp/lib/python3.9/site-packages/sigmadsp/sigmastudio/server.py", line 190, in handle_read_request
    response_header = self.server.packet_header_generator.new_header_from_operation_key(
  File "/home/pi/.local/pipx/venvs/sigmadsp/lib/python3.9/site-packages/sigmadsp/sigmastudio/header.py", line 359, in new_header_from_operation_key
    return self.new_header_from_operation_byte(int8_to_bytes(operation_key.value), template=template)
  File "/home/pi/.local/pipx/venvs/sigmadsp/lib/python3.9/site-packages/sigmadsp/sigmastudio/header.py", line 340, in new_header_from_operation_byte
    header.copy_from_template(template)
  File "/home/pi/.local/pipx/venvs/sigmadsp/lib/python3.9/site-packages/sigmadsp/sigmastudio/header.py", line 131, in copy_from_template
    self[field.name] = field.value
  File "/home/pi/.local/pipx/venvs/sigmadsp/lib/python3.9/site-packages/sigmadsp/sigmastudio/header.py", line 263, in __setitem__
    self._fields[name].value = value  # type: ignore
  File "/home/pi/.local/pipx/venvs/sigmadsp/lib/python3.9/site-packages/sigmadsp/sigmastudio/header.py", line 73, in value
    assert new_value.bit_length() <= self.size * 8, (
AssertionError: New value 2048 for 'address' exceeds expected size: expected <=8, got 12
```

**Comment by elagil** [comment] 2023-10-13 16:54
That helps. Please try v3.0.6 then.

However, I would still expect SigmaStudio to crash when reading all registers. There is a bug that has not been fixed yet.
See https://ez.analog.com/dsp/sigmadsp/f/q-a/563602/bug-sigma-studio-tcp-ip-completely-broken-after-update-to-4-6-also-to-4-7/477475
and also https://ez.analog.com/dsp/sigmadsp/f/q-a/563602/bug-sigma-studio-tcp-ip-completely-broken-after-update-to-4-6-also-to-4-7/477475

and some others...

**Comment by dbmaxpayne** [comment] 2023-10-13 17:55
Alright, now the error has changed again.

When I try to write a single register, I get
```
Exception occurred during processing of request from ('192.168.178.24', 64161)
Traceback (most recent call last):
  File "/usr/lib/python3.9/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.9/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.9/socketserver.py", line 720, in __init__
    self.handle()
  File "/home/pi/.local/pipx/venvs/sigmadsp/lib/python3.9/site-packages/sigmadsp/sigmastudio/server.py", line 234, in handle
    self.handle_read_request(packet)
  File "/home/pi/.local/pipx/venvs/sigmadsp/lib/python3.9/site-packages/sigmadsp/sigmastudio/server.py", line 194, in handle_read_request
    response_packet = Packet(response_header, read_response.data)
  File "/home/pi/.local/pipx/venvs/sigmadsp/lib/python3.9/site-packages/sigmadsp/sigmastudio/server.py", line 38, in __init__
    self.payload = payload
  File "/home/pi/.local/pipx/venvs/sigmadsp/lib/python3.9/site-packages/sigmadsp/sigmastudio/server.py", line 64, in payload
    if self.header["data_length"].value == 0:
  File "/home/pi/.local/pipx/venvs/sigmadsp/lib/python3.9/site-packages/sigmadsp/sigmastudio/header.py", line 277, in __getitem__
    return self._fields[name]
KeyError: 'data_length'
``` 

When I try to "Link Compile Download", I get
```
Exception in thread I2cProtocol handler thread:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/.local/pipx/venvs/sigmadsp/lib/python3.9/site-packages/sigmadsp/protocols/common.py", line 65, in serve_forever
    self._write(request.address, request.data)
  File "/home/pi/.local/pipx/venvs/sigmadsp/lib/python3.9/site-packages/sigmadsp/protocols/i2c.py", line 66, in _write
    self._bus.i2c_rdwr(msg_wr)
  File "/home/pi/.local/pipx/venvs/sigmadsp/lib/python3.9/site-packages/smbus2/smbus2.py", line 658, in i2c_rdwr
    ioctl(self.fd, I2C_RDWR, ioctl_data)
OSError: [Errno 121] Remote I/O error
``` 

This is the behaviour for SigmaStudio 3.15.
For 4.7 I get `Remote I/O error` for both, Register Write and Link Copile Download.

For example SigmaStudio 4.7 shows the following capture when I try to write a single register:
```
Block Write
Time:  19:51:11 - 213ms
IC:  IC 1
Param Name:  IC 1.SerialOutRegister1
Param Address:  0x081E
Bytes:  2
Param Data:
0x04, 	0x60
```

**Comment by elagil** [comment] 2023-10-14 07:06
The first one is another bug. I wonder how it ever worked with this chipset.

Using a simulated DSP, I will try to replicate these issues on my end.

**Comment by elagil** [comment] 2023-10-15 19:44
I tested with a Python-simulated ADAU1701 and I can write to it (compile/upload), as well as read all registers. Please try (v3.0.7).

**Comment by dbmaxpayne** [comment] 2023-10-16 06:15
Thanks again.
Unfortunately I now get a rather early error:
```
INFO:sigmadsp.backend:Starting the sigmadsp backend, version 3.0.8.
Traceback (most recent call last):
  File "/home/pi/.local/bin/sigmadsp-backend", line 8, in <module>
    sys.exit(main())
  File "/home/pi/.local/pipx/venvs/sigmadsp/lib/python3.9/site-packages/sigmadsp/backend.py", line 398, in main
    settings = SigmadspSettings(arguments.settings)
  File "/home/pi/.local/pipx/venvs/sigmadsp/lib/python3.9/site-packages/sigmadsp/helper/settings.py", line 34, in __init__
    with config_path.open(encoding="utf8") as settings_file:
AttributeError: 'str' object has no attribute 'open'
``` 

Off topic: How do you use a simulated DSP?

Cheers,
Mark

**Comment by elagil** [comment] 2023-10-16 06:42
Sorry, I introduced a new bug that wasn't detected by my tests and linters. It should be fixed in 3.0.9.

The simulated DSP is just an empty memory area from which SigmaStudio can request data, or where it can write data to. Since it does not use SPI or I2C, there is a "DummyProtocol" to act as a hardware interface to a DSP.

See https://github.com/blus-audio/sigmadsp/blob/main/app/dump_sigma_studio_data.py and
https://github.com/blus-audio/sigmadsp/blob/main/tests/mock/dummy_protocol.py

**Comment by dbmaxpayne** [comment] 2023-10-16 11:48
No worries, still a legend for programming this :)

After the new update I still got the `OSError: [Errno 121] Remote I/O error`.
I checked again with piscope what's happening on the bus and it didn't make sense.
Firstly I had to bit shift the ADAU1701's address by one bit as i2cdetect shows it as 0x50.
It's 0x68, though in 7-bit notation.
After putting 104 as the device_address the output looks better, but still off.

You can compare this here:
Working Link Compile Download sniffed from the USBi
![adau1701_fromUSBi](https://github.com/blus-audio/sigmadsp/assets/88050230/23f2d6d9-336f-450c-906e-d8b3fdfb893f)

Not working TCPi
![image](https://github.com/blus-audio/sigmadsp/assets/88050230/76452812-c0be-4b27-bc2e-bd8422671840)

As you can see there seems to be a problem with the start of the transmission.
It's somehow missing one clock pulse for the first 0 of the ADAU1701's address.

If I use pigpio with `pigs i2co 1 104 0` and a random read command (I know this wouldn't work, but just to see the first chip address bus intialization) `pigs i2cri 0 0x2a 1` the waveform looks extremely similar to the non-working TCPi one.
Here also the first 0 seems to be missing.

Strangely another I2C device which I can connect to the same bus works perfectly with pigs.

**Comment by dbmaxpayne** [comment] 2023-10-16 14:37
Mate, I got i working!

The device address is 52, not 88 and not 104.
Apparently you cannot rely on i2cdetect at all to find your addresses and somehow I got lost in the 7-bit address space conversion.

Everything is perfect when using 52 (decimal) / 0x34 (hex) as the device address.
i2cdetect shows 0x50 and the datasheet specifies 0x68 as the device address.
This is all super confusing, but now I got the hang of it.

Thanks again for fixing the initial bugs.

Now there's only one question left: Can I write the EEPROM with your tool?

Cheers,
Mark

**Comment by elagil** [comment] 2023-10-16 14:54
That's great to hear!

How is the EEPROM connected in your case? I usually write the EEPROM through my DSP (so yes, I can write EEPROM in my configuration).

**Comment by dbmaxpayne** [comment] 2023-10-16 16:13
I'm not a hundred percent sure as I don't have schematics of the board and cannot remove and inspect it from my project at the moment.
I only know that is is reachable via I2C at address 0xA0.
However, when I click on "Write Latest Compilation to E2PROM" in SigmaStudio it crashes.
So the question would be how that would work anyway.

**Comment by elagil** [comment] 2023-10-17 18:08
It seems like this is unsupported by SigmaStudio:
https://ez.analog.com/dsp/sigmadsp/f/q-a/115184/bug-report-sigma-studio-tcp-ip-read-from-dsp-with-temporary-solution
It will also be unsupported by SigmaStudio+, since that software doesn't even include modules for the ADAU1701/ADAU1401 DSPs.

We can extract the binary image that would be placed on the EEPROM, and then write it to the device. Extracting can be done like this: https://ez.analog.com/dsp/sigmadsp/f/q-a/66398/sigmastudio-creation-of-selfboot-image-hex-file

It would be quite a manual process, though (first extract, copy to RaspberryPi, flash).

**Closed** 2023-10-19 06:13 UTC
Labels: documentation
