### ISSUE TITLE
Could use some help please

### ISSUE THREAD

**Issue by musseilm** [blus-audio/sigmadsp#97] opened 2024-06-02 18:40 UTC
Trying to get this thing to run for my Adau1466 dsp.

Clean install of Rpi os Legacy bullseye 64bit with no desktop enviroment. On a Rpi zero 2w.
Installed the SigmaDsp as per the instructions. 
Edited the config.yaml with "I2c" and set the bus to "1"

The connection between SigmaStudio and the Rpi seems to work.
However when I hit Link Compile Download in SigmaStudio nothing seems to happen.

I hooked up  a Oscilloscope on Pin 3&5 Sda and Scl there is nothing happening with I hit Link Compile Download.

Any ideas?
Thanks

**Comment by musseilm** [comment] 2024-06-02 19:15
When I type "sigmadsp --help" I receive some errors...

admin@sigmadsp:~ $ sigmadsp --help
/home/admin/.local/share/pipx/venvs/sigmadsp/lib/python3.9/site-packages/gpiozer                                                                   o/devices.py:288: PinFactoryFallback: Falling back from rpigpio: No module named                                                                    'RPi'
  warnings.warn(
/home/admin/.local/share/pipx/venvs/sigmadsp/lib/python3.9/site-packages/gpiozer                                                                   o/devices.py:288: PinFactoryFallback: Falling back from lgpio: No module named '                                                                   lgpio'
  warnings.warn(
/home/admin/.local/share/pipx/venvs/sigmadsp/lib/python3.9/site-packages/gpiozer                                                                   o/devices.py:288: PinFactoryFallback: Falling back from rpio: No module named 'R                                                                   PIO'
  warnings.warn(
/home/admin/.local/share/pipx/venvs/sigmadsp/lib/python3.9/site-packages/gpiozer                                                                   o/devices.py:288: PinFactoryFallback: Falling back from pigpio: No module named                                                                    'pigpio'
  warnings.warn(
/home/admin/.local/share/pipx/venvs/sigmadsp/lib/python3.9/site-packages/gpiozer                                                                   o/devices.py:285: NativePinFactoryFallback: Falling back to the experimental pin                                                                    factory NativeFactory because no other pin factory could be loaded. For best re                                                                   sults, install RPi.GPIO or pigpio. See https://gpiozero.readthedocs.io/en/stable                                                                   /api_pins.html for more information.
  warnings.warn(NativePinFactoryFallback(native_fallback_message))
Usage: sigmadsp [OPTIONS] COMMAND [ARGS]...

**Comment by elagil** [comment] 2024-06-07 06:40
Hi @musseilm, I will look into it.

Did you enable I2C? Apparently, you need to to into `sudo raspi-config` and enable it there. See also https://pimylifeup.com/raspberry-pi-i2c/.

Let's see if that helps.

**Comment by elagil** [comment] 2024-06-12 10:58
@musseilm  I will try to replicate the issue. You mean the Raspberry Pi crashes completely? That would be quite bad.

**Comment by musseilm** [comment] 2024-06-16 14:19
Sorry for the delay, just back from vacation.
I guess I should rephrase the Rpi needs to be rebooted for the Sigma background service to work again. 
See attachment for the sigma studio file. See the picture of where to add a delay of lets say 10ms for the error to occur. 
Thank you
![Screenshot 2024-06-16 101715](https://github.com/blus-audio/sigmadsp/assets/47124477/d7d2bcd3-0bad-4206-b63e-03d134e6374b)
 
[TheDukeV4.zip](https://github.com/user-attachments/files/15858671/TheDukeV4.zip)

**Comment by musseilm** [comment] 2024-06-16 14:37
See below for the output of "sudo service sigmadsp-backend status"
First half is before adding a delay to the circuit, second half with a 20ms delay.
Looks like the service crashed?
![Screenshot 2024-06-16 103536](https://github.com/blus-audio/sigmadsp/assets/47124477/b98f12b6-72be-43fe-bdae-77115245b599)

**Comment by elagil** [comment] 2024-06-16 19:36
Yes, it did crash, thanks for the screenshots.

That seems to be I2C related, which I cannot easily test. I only have SPI devices. I will try to reproduce it anyway.

**Comment by musseilm** [comment] 2024-06-16 20:00
Let me know if there is something I could do.

**Comment by elagil** [comment] 2024-06-16 20:55
Yes, please use the version from my branch, which has extended logging. Maybe that helps us find the problem.
I tried running it, but without an I2C device on the bus, I get an immediate I/O error.

Please run the following to get that branch:
```bash
git clone https://github.com/blus-audio/sigmadsp.git # You might already have cloned the repository, so you may skip this step
cd sigmadsp
git fetch # Required, if cloned previously. Doesn't hurt in any case.
git switch fix-i2c-instability
pipx install . --force
sudo service sigmadsp-backend restart
```

**Comment by musseilm** [comment] 2024-06-16 21:07
Ok will do, how do I create a log?

**Comment by elagil** [comment] 2024-06-16 21:22
You should see the log messages it in the `status` output of the `sigmadsp-backend` service

**Comment by musseilm** [comment] 2024-06-17 16:54
After doing branch swap, I'm getting the following error.

![Screenshot 2024-06-17 125317](https://github.com/blus-audio/sigmadsp/assets/47124477/30e6c485-64a2-4a9c-8454-423c1de3db2f)

**Comment by musseilm** [comment] 2024-06-17 18:29
![Screenshot 2024-06-17 142927](https://github.com/blus-audio/sigmadsp/assets/47124477/5f3e1205-94a0-404a-a446-2e1ca7d721dc)

**Comment by elagil** [comment] 2024-06-17 18:54
Thanks for testing again.
You are on Python 3.9, while I am testing with 3.11, so I broke compatibility with your version (now fixed). Still, we don't see the original issue, but please pull the latest version:

```bash
cd ~/sigmadsp
git pull
pipx install . --force
sudo service sigmadsp-backend restart
```

**Comment by musseilm** [comment] 2024-06-17 19:10
Its working again. Here the result before and after with a delay added to the circuit. 

![Screenshot 2024-06-17 150952](https://github.com/blus-audio/sigmadsp/assets/47124477/12e8818d-def5-443d-bb0a-e4b7058e1fc1)

**Comment by elagil** [comment] 2024-06-17 19:14
I am missing a bit of the log. Maybe you can paste the output of `journalctl -u sigmadsp-backend --since=today` which gives the full logs of this day.

**Comment by musseilm** [comment] 2024-06-17 19:23
[log.txt](https://github.com/user-attachments/files/15876188/log.txt)

**Comment by elagil** [comment] 2024-06-17 20:22
Thanks, please repeat

```bash
cd ~/sigmadsp
git pull
pipx install . --force
sudo service sigmadsp-backend restart
```

I think that I am allowing to send an amount of data over I2C, which exceeds the maximum buffer size. I am now limiting it to a conservative 1024 bytes per transaction (like for SPI). This might help with the issue, if my assumption is correct, that this is indeed caused by an exceeded transmit buffer.

**Comment by musseilm** [comment] 2024-06-17 20:37
Seems like that might have solved the issue...

[log.txt](https://github.com/user-attachments/files/15876970/log.txt)

**Comment by elagil** [comment] 2024-06-17 20:44
If you don't get any more output than that, then there was no error. :+1: 

Maybe you can verify that the delay is working as intended?

**Comment by musseilm** [comment] 2024-06-17 20:48
Yes I tried and it seems to work. I will do some more testing tonight and will report back.

**Comment by elagil** [comment] 2024-06-17 20:56
Great. If you want to move back to the "official" release you can do:

```bash
pipx reinstall sigmadsp
rm -rf ~/sigmadsp
```

This will bring you to [v3.0.12](https://github.com/blus-audio/sigmadsp/releases/tag/v3.0.12).

**Comment by musseilm** [comment] 2024-06-18 18:21
Works flawless thanks a bunch! 👍

**Comment by elagil** [comment] 2024-06-19 10:55
Great! Thanks for the update.

**Closed by elagil** 2024-06-19 10:55 UTC
